services:
    n8nhackers-agent:
        environment:
            - N8NHACKERS_API_KEY=your_n8nhackers_api_key
            - INSTANCE_NAME1=n8n-name
            - INSTANCE_URL1=https://your-n8n.mydomain.com
            - INSTANCE_API_KEY1=your_n8n_api_key
        image: n8nhackers/agent:latest
        platform: linux/arm64
        networks:
            - default